### PR TITLE
Posibility of set group and chowns

### PR DESCRIPTION
**Pull request by zeleznypa**
Hi,

I want to use your great puppet module but I also want to use Git visualization tool like [GitLab](http://gitlab.org/) or [Gitlist](http://gitlist.org/). Unfortunately they both require to have read access to gitolite repositories directory for apache. 

With this pull-request you will be free to set group or every chmod.

### CODE REVIEW

**Comment by zeleznypa** [comment]
Hi @Spredzy ,

I also thought about separating $key_store but I found an error, when I set keystore to $home/.ssh directory which I thing is the best place for public ssh keys.  

Maybe you can move keystore section from line 80 at the and change condition to ` if ! defined(File[$keystore])

**Comment by Spredzy** [comment]
@zeleznypa please look at the last commit (d2807f35de), it should solve your issue.

The issue was happening if you were setting `$key_store` to any of the following values : 
- `${home}`
- `${home}/.ssh`
- `${home}/repositories`
- `${home}/gitolite`

The new check should take care of this. Can you run it and let me know if that's fine for your use case ?

Thanks,

**Comment by zeleznypa** [comment]
@Spredzy I tried last commit with following config

```
gitolite::instance {.
    'git':
        admin_pub_key         => 'ssh-rsa ...',
        home                  => '/home/git',
        key_store             => '/home/git',
        home_chmod            => '0755',
        repositories_chmod    => '0755',
}

```

but it returned me following error

```
err: Could not apply complete catalog: Found 1 dependency cycle:
(Exec[/home/git/gitolite/src/gitolite setup -pk /home/git/zeleznypa.pub] => File[/home/git/.ssh] => File[/home/git/zeleznypa.pub] => File[/home/git/.gitolite.rc] => Exec[/home/git/gitolite/src/gitolite setup -pk /home/git/zeleznypa.pub])
Try the '--graph' option and opening the resulting '.dot' file in OmniGraffle or GraphViz
```

**Comment by Spredzy** [comment]
@zeleznypa Sorry I missed this one, last commit (0c590150acb) took it in consideration

**Comment by zeleznypa** [comment]
@Spredzy Work like a charm. Thank's so much ;)

**Comment by zeleznypa** [comment]
@Spredzy Please let me know, when it will be available as module on Puppetlab ;)

**Comment by Spredzy** [comment]
@zeleznypa It's on the forge ;) Enjoy.

**Pull request merged**
